24.01.2019 08:22:49 Checking for system tray...
24.01.2019 08:22:52 Starting pgAdmin4 server...
24.01.2019 08:22:52 Creating server object, port:62288, key:1095a61d-e3ac-46d5-99fd-771ae4be4c6f, logfile:C:/Users/169121742018.2/.pgAdmin4.1590372639.log
24.01.2019 08:22:52 Python Path: C:/Program Files/PostgreSQL/11/pgAdmin 4/venv/Lib/site-packages;C:/Program Files/PostgreSQL/11/pgAdmin 4/venv/DLLs;C:/Program Files/PostgreSQL/11/pgAdmin 4/venv/Lib
24.01.2019 08:22:52 Python Home: C:/Program Files/PostgreSQL/11/pgAdmin 4/venv
24.01.2019 08:22:52 Initializing Python...
24.01.2019 08:22:53 Python initialized.
24.01.2019 08:22:53 Adding new additional path elements
24.01.2019 08:22:53 Redirecting stderr...
24.01.2019 08:22:53 stderr redirected successfully.
24.01.2019 08:22:53 Initializing server...
24.01.2019 08:22:53 Webapp Path: C:/Program Files/PostgreSQL/11/pgAdmin 4/web/pgAdmin4.py
24.01.2019 08:22:53 Server initialized.
24.01.2019 08:22:53 Starting Server Thread...
24.01.2019 08:22:53 Open the application code and run it.
24.01.2019 08:22:53 Set the port number, key and force SERVER_MODE off
24.01.2019 08:22:53 PyRun_SimpleFile launching application server...
24.01.2019 08:22:54 Application Server URL: http://127.0.0.1:62288/?key=1095a61d-e3ac-46d5-99fd-771ae4be4c6f
24.01.2019 08:22:54 The server should be up, we'll attempt to connect and get a response. Ping the server
24.01.2019 08:22:56 Attempt to connect one more time in case of a long network timeout while looping
24.01.2019 08:22:57 Everything works fine, successfully started pgAdmin4.
